homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude:  !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret ele
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin

  customize_glob: !include customize_glob.yaml
  customize:      !include customize.yaml
  packages:       !include_dir_named packages

#automation: !include automations.yaml
automation old: !include_dir_merge_list    automation/

binary_sensor:  !include_dir_merge_list    binary_sensors/
camera:         !include_dir_merge_list    camera/
climate:        !include_dir_merge_list    climate/
input_boolean:  !include_dir_merge_named   input_boolean/
input_datetime: !include_dir_merge_named   input_datetime/
input_number:   !include_dir_merge_named   input_number/
input_select:   !include_dir_merge_named   input_select/
light:          !include_dir_merge_list    light/
media_player:   !include_dir_merge_list    media_player/
sensor:         !include_dir_merge_list    sensors/
shell_command:  !include_dir_merge_named   shell_commands/
switch:         !include_dir_merge_list    switch/

#group:          !include_dir_merge_named group/
scene:          !include_dir_merge_list scenes/

alexa:          !include alexa/alexa.yaml

vacuum:
  - platform: xiaomi_miio
    host: 192.168.178.145
    token: !secret mi_robot_token
    name: Mi Robot Vacuum
    
# Enables the frontend
frontend:
  javascript_version: latest
# Enables configuration UI
config:

hassio:

discovery:
  ignore:
    - google_cast
    - philips_hue
    - igd
    
http:
  # ssl_certificate: !secret http_ssl_certificate
  # ssl_key: !secret http_ssl_key
  base_url: !secret http_base_url
  # api_password: !secret http_api_password
  ip_ban_enabled: true
  login_attempts_threshold: 3


# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  reporting: False
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:
history:
  include:
    domains:
      - climate
  exclude:
    entities:
      - climate.prototype

# The recorder component is storing details in a database which then are handled by the history component.
recorder:
  purge_interval: 1
  purge_keep_days: 7

# The logbook component provides a different perspective on the history of your house by showing all the changes that happened to your house in reverse chronological order.
logbook:

#iframes
panel_iframe: !include_dir_merge_named iframes/

#InfluxDB
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: !secret influxdb_dbname
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 10
  default_measurement: state

notify:
  - name: slack_notify
    platform: slack
    api_key: !secret slack_api_key
    default_channel: '#allgemein'

# Track the sun
sun:
  
#MQTT
# mqtt:
#   broker: !secret mqtt_broker
#   port: !secret mqtt_port
#   client_id: !secret mqtt_client_id
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   discovery: true
#   discovery_prefix: homeassistant

#Octoprint
octoprint:
  host: !secret octoprint_host
  api_key: !secret octoprint_api_key
  bed: True
  number_of_tools: 1

#hubs
enocean:
  device: /dev/ttyUSB1
  
zha:
  usb_path: /dev/ttyUSB0
  database_path: zigbee.db
  baudrate: 57600
  
cover:
  - platform: duofern
    serial_port: /dev/ttyUSB2
    config_file: duofern.json
    code: 1234

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: qzdtjzt6vxzo892k

logger:
  default: warn
  # logs:
  #   homeassistant.components.mqtt: debug