homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude:  !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret ele
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin

  customize_glob: !include customize_glob.yaml

  customize: !include customize.yaml
  
  packages: !include_dir_named packages

camera: !include_dir_merge_list camera/
#media_player: !include_dir_merge_list media_player/
climate: !include_dir_merge_list climate/
light: !include_dir_merge_list light/
switch: !include_dir_merge_list switch/
input_number: !include_dir_merge_named input_number/
input_select: !include_dir_merge_named input_select/
input_datetime: !include_dir_merge_named input_datetime/
sensor: !include_dir_merge_list sensors/
shell_command: !include_dir_merge_named shell_commands/
binary_sensor: !include_dir_merge_list binary_sensors/
input_boolean: !include_dir_merge_named input_boolean/
group: !include_dir_merge_named group/
scene: !include_dir_merge_list scenes/
automation: !include_dir_merge_list automation/

alexa: !include alexa/alexa.yaml



vacuum:
  - platform: xiaomi_miio
    host: 192.168.178.145
    token: 6b72505a65675139754e59416c466669
    name: Mi Robot Vacuum
    
# Enables the frontend
frontend:
  javascript_version: latest
# Enables configuration UI
config:
hassio:

http:
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key
  base_url: !secret http_base_url
  trusted_networks: !secret http_trusted_networks
  api_password: !secret http_api_password

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  reporting: False
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# The recorder component is storing details in a database which then are handled by the history component.
recorder:
  purge_interval: 1
  purge_keep_days: 180

# The history component will track everything that is going on within Home Assistant and allows the user to browse through it. It depends on the recorder component for storing the data and uses the same database setting. If any entities are excluded from being recorded, no history will be available for these entities.
history:
  include:
    entities: !include_dir_merge_list history/

# The logbook component provides a different perspective on the history of your house by showing all the changes that happened to your house in reverse chronological order.
logbook:

# View all events in a logbook
#logbook:

# Track the sun
sun:
  
#MQTT
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant

#Octoprint
octoprint:
  host: !secret octoprint_host
  api_key: !secret octoprint_api_key
  bed: True
  number_of_tools: 1

#hubs
enocean:
  device: /dev/ttyUSB1
  
zha:
  usb_path: /dev/ttyUSB0
  database_path: zigbee.db
  baudrate: 57600
  
cover:
  - platform: duofern
    serial_port: /dev/ttyUSB2
    config_file: duofern.json
    code: 1234

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: qzdtjzt6vxzo892k

###
logger:
  default: warn
  logs:
    homeassistant.components.zha: debug
    bellows.ezsp: debug
    bellows.uart: debug
    zigpy.zdo: debug
    zigpy.application: debug