homeassistant:
  customize_glob: !include customize_glob.yaml
  customize:      !include customize.yaml
  packages:       !include_dir_named packages

automation:     !include automations.yaml
automation old: !include_dir_merge_list    automation/

binary_sensor:  !include_dir_merge_list    binary_sensors/
camera:         !include_dir_merge_list    camera/
device_tracker: !include_dir_merge_list    device_tracker/
input_boolean:  !include_dir_merge_named   input_boolean/
input_datetime: !include_dir_merge_named   input_datetime/
input_number:   !include_dir_merge_named   input_number/
input_select:   !include_dir_merge_named   input_select/
light:          !include_dir_merge_list    light/
media_player:   !include_dir_merge_list    media_player/
sensor:         !include_dir_merge_list    sensors/
script:         !include_dir_merge_list    scripts/
shell_command:  !include_dir_merge_named   shell_commands/
switch:         !include_dir_merge_list    switch/
script:         !include scripts.yaml
scene:          !include_dir_merge_list scenes/
panel_iframe:   !include_dir_merge_named iframes/
alexa:          !include alexa/alexa.yaml

person:

# for camera
ffmpeg:
stream:

tplink:
  switch:
    - host: !secret hs100_ip

system_health:

speedtestdotnet:
  manual: true
  monitored_conditions:
    - ping
    - download
    - upload

hacs:
  token: fbebd3b4d45e7b0b853d1ca0358fc0d8a9a88717

vacuum:
  - platform: xiaomi_miio
    host: !secret mi_robot_ip
    token: !secret mi_robot_token
    name: Mi Robot Vacuum
    
# Enables the frontend
frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

mobile_app:

hassio:

discovery:
  ignore:
    - google_cast
    - philips_hue
    
http:
  base_url: !secret http_base_url

updater:
  reporting: False

recorder:
  db_url: !secret mariaDB_url
  purge_keep_days: 30

logbook:

influxdb:
  host: a0d7b954-influxdb
  port: !secret influxdb_port
  database: !secret influxdb_dbname
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 99

notify:

sun:

octoprint:
  host: !secret octoprint_host
  port: !secret octoprint_port
  api_key: !secret octoprint_api_key
  bed: True
  number_of_tools: 1

logger:
  default: warn

#hubs
duofern:
  serial_port: /dev/serial/by-id/usb-Rademacher_DuoFern_USB-Stick_WR06IAWA-if00-port0
  config_file: duofern.json
  code: !secret duofern_code

enocean:
  device: /dev/serial/by-id/usb-EnOcean_GmbH_EnOcean_USB_300_DB_FT1M2KBN-if00-port0
