homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude:  !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret ele
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin

  customize_glob: !include customize_glob.yaml
  customize:      !include customize.yaml
  packages:       !include_dir_named packages

#automation: !include automations.yaml
automation old: !include_dir_merge_list    automation/

binary_sensor:  !include_dir_merge_list    binary_sensors/
camera:         !include_dir_merge_list    camera/
device_tracker: !include_dir_merge_list    device_tracker/
input_boolean:  !include_dir_merge_named   input_boolean/
input_datetime: !include_dir_merge_named   input_datetime/
input_number:   !include_dir_merge_named   input_number/
input_select:   !include_dir_merge_named   input_select/
light:          !include_dir_merge_list    light/
media_player:   !include_dir_merge_list    media_player/
sensor:         !include_dir_merge_list    sensors/
shell_command:  !include_dir_merge_named   shell_commands/
# switch:         !include_dir_merge_list    switch/
script:         !include_dir_merge_named   scripts/
#group:          !include_dir_merge_named group/
scene:          !include_dir_merge_list scenes/
panel_iframe:   !include_dir_merge_named iframes/
alexa:          !include alexa/alexa.yaml

tplink:
  switch:
    - host: !secret hs100_ip

system_health:

speedtestdotnet:
  scan_interval:
    days: 1
  monitored_conditions:
    - ping
    - download
    - upload

vacuum:
  - platform: xiaomi_miio
    host: !secret mi_robot_ip
    token: !secret mi_robot_token
    name: Mi Robot Vacuum
    
# Enables the frontend
frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes

# lovelace:
#   mode: yaml

# Enables configuration UI
config:

hassio:

discovery:
  ignore:
    - google_cast
    - philips_hue
    
http:
  base_url: !secret http_base_url

updater:
  reporting: False

# history:
#   include:
#     domains:
#       - climate
#   exclude:
#     entities:
#       - climate.prototype

# The recorder component is storing details in a database which then are handled by the history component.
recorder:
  db_url: !secret mariaDB_url
  purge_interval: 1
  purge_keep_days: 30

# The logbook component provides a different perspective on the history of your house by showing all the changes that happened to your house in reverse chronological order.
logbook:

#InfluxDB
influxdb:
  host: a0d7b954-influxdb
  port: !secret influxdb_port
  database: !secret influxdb_dbname
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 99

notify:
  - name: slack_notify
    platform: slack
    api_key: !secret slack_api_key
    default_channel: '#allgemein'

# Track the sun
sun:

#Octoprint
octoprint:
  host: !secret octoprint_host
  port: !secret octoprint_port
  api_key: !secret octoprint_api_key
  bed: True
  number_of_tools: 1

#hubs
duofern:
  serial_port: /dev/ttyUSB0
  config_file: duofern.json
  code: !secret duofern_code

enocean:
  device: /dev/ttyUSB1

# zha:
#   usb_path: /dev/ttyUSB1
#   database_path: zigbee.db
#   baudrate: 57600

# xiaomi_aqara:
#   discovery_retry: 10
#   gateways:
#     - key: !secret aqara_key

logger:
  default: warn