title: Home
views:
  #view Home
  - title: Home
    icon: mdi:home-assistant
    cards:
      #card
      - type: entities
        title: Licht
        show_header_toggle: true
        entities:
          - switch.s20_1
          - switch.s20_4
          - switch.s20_2
          - switch.steckdose_hs100_1
          # - entity: switch.s20_3
          #   name: Stern
          #   icon: mdi:star
          - switch.shelly1_01
          - switch.shelly1_02
      #card
      - type: sensor
        entity: sensor.temperature_158d0002281a4e
      #card stack
      - type: vertical-stack
        cards:
          #card
          - type: thermostat
            entity: climate.buero
          #card
          - type: thermostat
            entity:  climate.wohnzimmer
      #card
      - type: entities
        title: Staubsauger
        show_header_toggle: true
        entities:
          - vacuum.mi_robot_vacuum
      #card
      - type: entities
        title: Rollladen
        show_header_toggle: false
        entities:
          - cover.wohnzimmer
  #view Licht
  - title: Licht
    icon: mdi:lightbulb-on-outline
    cards:
      #card
      - type: entities
        title: Allgemein
        show_header_toggle: true
        entities:
          - switch.s20_1
          - switch.s20_4
          - switch.s20_2
          - switch.steckdose_hs100_1
          # - entity: switch.s20_3
          #   name: Stern
          #   icon: mdi:star
      #card
      - type: entities
        title: Büro
        show_header_toggle: false
        entities:
          - entity: switch.shelly1_01
            name: Deckenlicht
            icon: mdi:ceiling-light
          - entity: input_number.illuminance_threshold_buero
          - entity: sensor.illumination_158d000200ceec
            name: Helligkeitssensor
          - entity: binary_sensor.motion_sensor_158d000200ceec
            name: Bewegungssensor
          - input_boolean.buero_licht_wegen_bewegung
          - light.led_strip

      #card
      - type: entities
        title: Treppe oben
        show_header_toggle: false
        entities:
          - switch.shelly1_02
          - entity: input_number.illuminance_threshold_treppe_oben
          - entity: sensor.illumination_158d0001fa3d9c
            name: Helligkeitssensor
          - entity: binary_sensor.motion_sensor_158d0001fa3d9c
            name: Bewegungssensor
          - input_boolean.treppe_oben_licht_wegen_bewegung

  #view Media
  - title: Media
    icon: mdi:audio-video
    cards:
      #card
      - type: media-control
        entity: media_player.denon_avr

  #view Szenen
  - title: Szenen
    icon: mdi:arrow-decision-outline
    cards:
      #card
      - type: entities
        title: Szenes
        show_header_toggle: false
        entities:
          - entity: scene.fernsehabend
            icon: mdi:television-box

  #view Heizung
  - title: Heizung
    icon: mdi:thermostat
    cards:
      #card stack
      - type: vertical-stack
        cards:
          #card
          - type: thermostat
            entity: climate.buero
          #card
          # - type: entities
          #   entities:
          #     - climate.buero
          #card
          - type: sensor
            entity: sensor.temperatur_buero
            name: Büro

      #card stack
      - type: vertical-stack
        cards:
          #card
          - type: thermostat
            entity: climate.wohnzimmer
          #card
          # - type: entities
          #   entities:
          #     - climate.wohnzimmer
          #card
          - type: sensor
            entity: sensor.temperatur_wohnzimmer
            name: Wohnzimmer
  #view
  - title: Maker
    icon: mdi:printer-3d
    cards:
      #card
      - type: entities
        title: Maker
        show_header_toggle: false
        entities:
          - switch.s20_5
          - switch.s20_6
          - entity: sensor.octoprint_actual_bed_temp
            name: Druckbett Temperatur
          - entity: sensor.octoprint_target_bed_temp
            name: Druckbett Solltemperatur
          - entity: sensor.octoprint_actual_tool0_temp
            name: Druckkopf Temperatur
          - entity: sensor.octoprint_target_tool0_temp
            name: Druckkopf Solltemperatur
          - entity: sensor.octoprint_current_state
            name: Status
            icon: mdi:printer-alert
          - entity: sensor.octoprint_job_percentage
            name: Druckfortschritt
            icon: mdi:progress-clock
          - entity: sensor.octoprint_time_elapsed
            name: Druckzeit
          - entity: sensor.octoprint_time_remaining
            name: Restzeit
          - entity: input_boolean.drucker_nach_druck_aus
            name: Drucker und Licht nach Druck Ausschalten
            icon: mdi:progress-check

      #card
      - type: picture-entity
        name: OctoPrint Cam
        entity: camera.octoprint
        camera_image: camera.octoprint
        show_info: false
        show_state: false
        tap_action: dialog
  #view
  - title: Outdoor
    cards:
      - type: entities
        #title: Outdoor
        show_header_toggle: false
        entities:
          - entity: switch.funksteckdose_aussen
            name: Außensteckdose
  #view
  - title: Automation
    cards:
      #card
      - type: entities
        show_header_toggle: false
        entities:
          - input_boolean.aussensteckdose_automation
          - input_select.zeitsteuerung
      #conditional
      - type: conditional
        conditions:
          - entity: input_select.zeitsteuerung
            state: "Zeit"
        #card
        card:
          type: entities
          title: Zeit
          show_header_toggle: false
          entities:
            - input_datetime.beleuchtung_morgens_an
            - input_datetime.beleuchtung_morgens_aus
            - input_datetime.beleuchtung_abends_an
            - input_datetime.beleuchtung_abends_aus
      #conditional
      - type: conditional
        conditions:
          - entity: input_select.zeitsteuerung
            state: "Zeit und Sonne"
        #card
        card:
          type: entities
          title: Zeit und Sonne
          show_header_toggle: false
          entities:
            - input_datetime.beleuchtung_morgens_an
            - sensor.sunrise_time
            - sensor.sunset_time
            - input_datetime.beleuchtung_abends_aus

  #view Admin
  - title: Admin
    cards:
      #card
      - type: entities
        title: Admin General
        show_header_toggle: false
        entities:
          - sensor.current_version
          - sensor.time
          - sensor.processor_use
          - sensor.memory_free
          - sensor.disk_free_
          - sensor.last_boot
          - input_boolean.update_thermostats
          - sensor.speedtest_download
          - sensor.speedtest_upload
          - sensor.speedtest_ping
          - sensor.rf_receiver
          - entity: sensor.sunrise_time
            name: Sonnenaufgang
          - entity: sensor.sunset_time
            name: Sonnenuntergang

      #card
      - type: entities
        title: Xiaomi Zigbee
        show_header_toggle: false
        entities:
          - binary_sensor.motion_sensor_158d000200ce5c
          - sensor.illumination_158d000200ce5c
          - binary_sensor.motion_sensor_158d0001fa3d9c
          - sensor.illumination_158d0001fa3d9c
          - binary_sensor.motion_sensor_158d000200ceec
          - sensor.illumination_158d000200ceec
          - light.gateway_light_7811dc6c97d5
          - sensor.illumination_7811dc6c97d5
          - sensor.temperature_158d0002281a4e
          - sensor.humidity_158d0002281a4e
      #vertical stack
      - type: vertical-stack
        cards:
        #card
        - type: entities
          title: Battery Alert
          show_header_toggle: false
          entities:
            - input_number.battery_alert_threshold_min
            - input_number.battery_alert_threshold_max
            - automation.battery_notification
            - automation.battery_notification_clear
            - automation.battery_notification_slack
            - automation.battery_sensor_from_battery_level_attribute
            - automation.battery_sensor_from_battery_attribute
            - automation.battery_sensor_from_battery_numeric_attribute
            - automation.update_battery_status_group_members
        #card
        - type: entities
          title: Battery Status
          show_header_toggle: false
          entities:
            - sensor.aussentemperatur_battery
            - sensor.humidity_158d0002281a4e_battery
            - sensor.illumination_158d0001fa3d9c_battery
            - sensor.illumination_158d000200ce5c_battery
            - sensor.illumination_158d000200ceec_battery
            - sensor.mi_robot_vacuum_battery
            - sensor.motion_sensor_158d0001fa3d9c_battery
            - sensor.motion_sensor_158d000200ce5c_battery
            - sensor.motion_sensor_158d000200ceec_battery
      #card
      - type: entities
        title: DuoFern
        show_header_toggle: false
        entities:
          - sensor.duofern_paired_devices
          - sensor.duofern_system_code

      #card
      - type: entities
        title: Buero
        show_header_toggle: false
        entities:
          - climate.buero
          - sensor.temperatur_buero
          - sensor.luftfeuchtigkeit_buero
          - binary_sensor.sensorfehler_buero
          - sensor.firmware_buero
          - switch.firmwareupdate_buero
          - switch.neustart_buero
          - sensor.ip_buero
          - sensor.skalierung_buero
          - sensor.offset_buero
      #card
      - type: entities
        title: Wohnzimmer
        show_header_toggle: false
        entities:
          - climate.wohnzimmer
          - sensor.temperatur_wohnzimmer
          - sensor.luftfeuchtigkeit_wohnzimmer
          - binary_sensor.sensorfehler_wohnzimmer
          - sensor.firmware_wohnzimmer
          - switch.firmwareupdate_wohnzimmer
          - switch.neustart_wohnzimmer
          - sensor.ip_wohnzimmer
          - sensor.skalierung_wohnzimmer
          - sensor.offset_wohnzimmer
      #card
      - type: entities
        title: Prototype
        show_header_toggle: false
        entities:
          - entity: climate.prototype
            name: Prototype
          - sensor.temperatur_prototype
          - sensor.luftfeuchtigkeit_prototype
          - binary_sensor.sensorfehler_prototype
          - sensor.firmware_prototype
          - switch.firmwareupdate_prototype
          - switch.neustart_prototype
          - sensor.ip_prototype
          - sensor.skalierung_prototype
          - sensor.offset_prototype
#{{ADMINCARD}}