  marderschreck_auto_group:
    name: Zeitsteuerung Marderschreck
    control: hidden
    entities:
      - input_boolean.aussensteckdose_automation

  beleuchtung_auto_select_group:
    name: Zeitsteuerung Szene Beleuchtung
    control: hidden
    entities:
      - input_select.zeitsteuerung
      
  beleuchtung_timer_auto_group:
    name: Zeit
    control: hidden
    entities:
      - input_datetime.beleuchtung_morgens_an
      - input_datetime.beleuchtung_morgens_aus
      - input_datetime.beleuchtung_abends_an
      - input_datetime.beleuchtung_abends_aus
      
  beleuchtung_sonne_auto_group:
    name: 'Zeit und Sonne'
    control: hidden
    entities:
      - input_datetime.beleuchtung_morgens_an
      - sensor.sunrise_time
      - sensor.sunset_time
      - input_datetime.beleuchtung_abends_aus