  drucker_nach_druck_aus:
    name: Drucker nach Druck ausschalten
    icon: mdi:toggle-switch-off
 
  automation_licht_buero:
    name: Bewegungssteuerung

  automation_licht_treppe_oben:
    name: Bewegungssteuerung

  automation_licht_treppe_unten:
    name: Bewegungssteuerung
