  beleuchtung_automation_timer:
    name: Beleuchtung Zeitsteuerung
    initial: off
    icon: mdi:home-automation

  beleuchtung_automation_sonne:
    name: Beleuchtung Sonnensteuerung
    initial: on
    icon: mdi:home-automation

  aussensteckdose_automation:
    name: Außensteckdose
    initial: on
    icon: mdi:home-automation